//! The TideDesk icon for windows (and the tray), generated by `tools/make_icon.py`.

pub const SIZE: u32 = 64;

pub fn rgba() -> Vec<u8> {
    include_bytes!("../../../assets/tidedesk-64.rgba").to_vec()
}

pub fn egui_icon() -> std::sync::Arc<egui::IconData> {
    std::sync::Arc::new(egui::IconData {
        rgba: rgba(),
        width: SIZE,
        height: SIZE,
    })
}
